"""empty message

Revision ID: 9ff2997211b8
Revises: 
Create Date: 2022-05-02 16:35:37.243395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff2997211b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('confirmed_cases', sa.Integer(), nullable=True),
    sa.Column('recovered_cases', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('sq_km_area', sa.Integer(), nullable=True),
    sa.Column('continent', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('capital_city', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('long', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
